# Generated by Django 3.1.1 on 2020-09-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('I', 'Image'), ('V', 'Video'), ('A', 'Audio')], default='I', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.FileField(blank=True, upload_to='posts'),
        ),
    ]
