# Generated by Django 3.0.8 on 2020-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200802_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
