# Generated by Django 3.0.8 on 2020-08-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=12)),
                ('portfolio_site', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('resume', models.FileField(blank=True, upload_to='resumes')),
                ('profile_pic', models.ImageField(blank=True, default='profilepics/default1.jpg', upload_to='profilepics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
